In [1]:
import numpy as np
from datetime import datetime

In [2]:
"""
1. Python	Sınıfı	Oluşturma
"""
class Kitap:
    def __init__(self, baslik: str, yazar: str, yayin_yili: int, sayfa_sayisi: int, diller: list[str]):
        self.baslik = baslik
        self.yazar = yazar
        self.yayin_yili = yayin_yili
        self.sayfa_sayisi = sayfa_sayisi
        self.diller = diller

    def dil_ekle(self, dil: str):
        self.diller.append(dil) #Yeni bir dil eklemek için

    def kitap_yasi_hesapla(self) -> int:
        return datetime.now().year - self.yayin_yili #Kitabın yaşını yayın yılına göre hesaplaması

    def kitap_goruntule(self, paragraf: bool = False):
        if paragraf:
            print(
                f"'{self.baslik}' başlıklı kitap, {self.yazar} tarafından yazılmıştır. "
                f"İlk olarak {self.yayin_yili} yılında yayımlanmış olan bu kitap, toplam {self.sayfa_sayisi} sayfadan oluşmaktadır. "
                f"Şu an için bu kitap, {', '.join(self.diller)} dillerinde bulunmaktadır."
            )
        else:
            # Satır bazlı görüntüleme
            print(f"Başlık: {self.baslik}")
            print(f"Yazar: {self.yazar}")
            print(f"Yayın Yılı: {self.yayin_yili}")
            print(f"Sayfa Sayısı: {self.sayfa_sayisi}")
            print(f"Diller: {', '.join(self.diller)}")

kitap = Kitap(
   baslik="Programlama Temelleri",
   yazar="Olvanot Jean Claude Rakotonirina",
   yayin_yili=2005,
   sayfa_sayisi=92,
   diller=["Türkçe", "İngilizce"]
)

kitap.dil_ekle("Fransızca")
kitap.kitap_goruntule(paragraf=True)
print("****")
kitap.kitap_goruntule(paragraf=False)

'Programlama Temelleri' başlıklı kitap, Olvanot Jean Claude Rakotonirina tarafından yazılmıştır. İlk olarak 2005 yılında yayımlanmış olan bu kitap, toplam 92 sayfadan oluşmaktadır. Şu an için bu kitap, Türkçe, İngilizce, Fransızca dillerinde bulunmaktadır.
****
Başlık: Programlama Temelleri
Yazar: Olvanot Jean Claude Rakotonirina
Yayın Yılı: 2005
Sayfa Sayısı: 92
Diller: Türkçe, İngilizce, Fransızca


In [3]:
"""
2. Gelişmiş NumPy İşlemleri
"""

#Min/Max Değerleri ve İndeksleri
row_dict = dict()
matrix = np.random.randint(0, 100, (10, 10)) # 10x10 boyutunda rastgele tam sayı
for i in range(10):
    min_value = np.min(matrix[i])
    max_value = np.max(matrix[i])
    
    min_index = np.argmin(matrix[i]) 
    max_index = np.argmax(matrix[i])
    
    # Satırların min, max değerleri ve indekslerini sözlükte tutulması
    row_dict[i] = [(min_value, min_index), (max_value, max_index)]
    
print(matrix)
print("Min/Max Değerleri ve İndeksleri")
print(row_dict)

[[62 63 11 22 18 69 40 74 64 62]
 [75  6 86 11 13 29 77 65 40 64]
 [88 19 31 45 31 87 84 39  8 63]
 [21 65 35 50 33 95 85 21 31 80]
 [20 84 76  0 69 79 16 85 11 46]
 [ 8 41  6 61 97  7 46 93 11 28]
 [ 3 94  5 60 64 18 48 94 38 72]
 [38 79 34 31 29 14 37 11 60 72]
 [34 35 80 74 75 31  1 77 12 89]
 [66 55  0 10 45 50  9  5 38 88]]
Min/Max Değerleri ve İndeksleri
{0: [(np.int32(11), np.int64(2)), (np.int32(74), np.int64(7))], 1: [(np.int32(6), np.int64(1)), (np.int32(86), np.int64(2))], 2: [(np.int32(8), np.int64(8)), (np.int32(88), np.int64(0))], 3: [(np.int32(21), np.int64(0)), (np.int32(95), np.int64(5))], 4: [(np.int32(0), np.int64(3)), (np.int32(85), np.int64(7))], 5: [(np.int32(6), np.int64(2)), (np.int32(97), np.int64(4))], 6: [(np.int32(3), np.int64(0)), (np.int32(94), np.int64(1))], 7: [(np.int32(11), np.int64(7)), (np.int32(79), np.int64(1))], 8: [(np.int32(1), np.int64(6)), (np.int32(89), np.int64(9))], 9: [(np.int32(0), np.int64(2)), (np.int32(88), np.int64(9))]}


In [4]:
# Her sütunun ortalama, medyan ve standart sapma 
col_dict = dict()

matrix = np.random.randint(0, 100, (10, 10)) # 10x10 boyutunda rastgele tam sayı

for col_index in range(10):
    column_mean = np.mean(matrix[:, col_index])
    column_median = np.median(matrix[:, col_index])
    column_standart_deviation = np.std(matrix[:, col_index]) 
    
    col_dict[col_index] = {
        'mean': column_mean,
        'median': column_median,
        'standart_deviation': column_standart_deviation 
    }
print(matrix)
print("Her sütunun ortalama, medyan ve standart sapma değerleri:")
print(col_dict)


[[16 29 77 14 97 64  0 66 49 21]
 [41 42 13 76  5  7 60 81  3 62]
 [44  2 59 31 65 79 72 92 96 27]
 [10 48 43 73 69 81 39  2 84 51]
 [59 43  2 97 78 55 91 22 44 90]
 [96 86  6 29  1 96 35 98 22 94]
 [79  2 38 64 12 41 34 28 36 80]
 [29 56 75 77 84 87 46 40 18 98]
 [20 88 64 17 41 38 74 86 56 95]
 [37 52 51  2  4 35 10 45 23 77]]
Her sütunun ortalama, medyan ve standart sapma değerleri:
{0: {'mean': np.float64(43.1), 'median': np.float64(39.0), 'standart_deviation': np.float64(26.3531781764553)}, 1: {'mean': np.float64(44.8), 'median': np.float64(45.5), 'standart_deviation': np.float64(27.70487321754063)}, 2: {'mean': np.float64(42.8), 'median': np.float64(47.0), 'standart_deviation': np.float64(26.297528400973352)}, 3: {'mean': np.float64(48.0), 'median': np.float64(47.5), 'standart_deviation': np.float64(31.28897569432403)}, 4: {'mean': np.float64(45.6), 'median': np.float64(53.0), 'standart_deviation': np.float64(35.50830888679437)}, 5: {'mean': np.float64(58.3), 'median': np.float64

In [5]:
"""
3. Matris	Çarpımı
"""

def max_in_rows_of_product(matrix_A, matrix_B):
    matrix_AxB = np.dot(matrix_A, matrix_B)
    max_values_in_rows = np.max(matrix_AxB, axis=1) 
    print("A X B:")
    print(matrix_AxB)
    return max_values_in_rows

matrix_A = np.array([[2, 3, 4], [1, 0, 6]])
matrix_B = np.array([[1, 4], [2, 5], [3, 6]])

max_values = max_in_rows_of_product(matrix_A, matrix_B)

print("Sonuç: Matris A x Matris B çarpımındaki her satırın en büyük değerleri:")
print(max_values)


A X B:
[[20 47]
 [19 40]]
Sonuç: Matris A x Matris B çarpımındaki her satırın en büyük değerleri:
[47 40]


In [6]:
"""
4. Faktöriyel	Hesaplama
"""
def factorial_with_loop(n):
    if n < 0:
        return "Faktöriyel yalnızca pozitif tam sayı olmalıdır!"
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

def factorial(n):
    if n < 0:
        return "Faktöriyel yalnızca pozitif tam sayı olmalıdır!"
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

number=10
print(f"{number}! = {factorial_with_loop(number)}")
print(f"{number}! = {factorial(number)}")


10! = 3628800
10! = 3628800


In [7]:

"""
5. Rasgele	Dizi İşlemleri
"""
random_integers = np.random.randint(1, 21, (5, 4))
print("***Rasgele dizi:***")
print(random_integers)
row_sums = np.sum(random_integers, axis=1)  
row_means = np.mean(random_integers, axis=1) 
row_stats = np.column_stack((row_sums, row_means))  # we can use  np.vstack((row_sums, row_means)).T and Transposing

print("***Satır toplamları***")
print(row_sums)
print("***Satır ortalamaları***")
print(row_means)
# print("******")
print("Satırların Toplam ve Ortalamaları:\n", row_stats)

column_max = np.max(random_integers, axis=0) 
column_min = np.min(random_integers, axis=0)
column_max_min = np.column_stack((column_max, column_min))  # Yeni bir dizi oluştur
print("Sütunların Maksimum ve Minimum Değerleri:\n", column_max_min)

"""
ÇİFT MATRIS İÇİN:
Yaklaşım: Tek Sayılara 1 Ekleme
Bu yöntemde, tek sayılara 1 eklenerek çift yapılır, çift sayılar ise olduğu gibi bırakılır

Eğer random_integers = [3, 4, 7, 8] ise:
random_integers % 2 → [1, 0, 1, 0]
(3 ve 7 için kalan 1, 4 ve 8 için 0.)
random_integers + (random_integers % 2) → [4, 4, 8, 8]
"""
even_matrix = random_integers + (random_integers % 2)
print("Çift matris:\n", even_matrix)


***Rasgele dizi:***
[[16 15 15  8]
 [10  5 19 11]
 [ 6  5 10 14]
 [ 8 14 16  8]
 [19 12 19  9]]
***Satır toplamları***
[54 45 35 46 59]
***Satır ortalamaları***
[13.5  11.25  8.75 11.5  14.75]
Satırların Toplam ve Ortalamaları:
 [[54.   13.5 ]
 [45.   11.25]
 [35.    8.75]
 [46.   11.5 ]
 [59.   14.75]]
Sütunların Maksimum ve Minimum Değerleri:
 [[19  6]
 [15  5]
 [19 10]
 [14  8]]
Çift matris:
 [[16 16 16  8]
 [10  6 20 12]
 [ 6  6 10 14]
 [ 8 14 16  8]
 [20 12 20 10]]


In [8]:
"""
6. Büyük NumPy	Dizisi Analizi
"""
random_integers = np.random.randint(1, 101, size=30)

#DİZİDEKİ EN KÜÇÜK, EN BÜYÜK VE MEDYAN DEĞERİ
min_value = np.min(random_integers)  
max_value = np.max(random_integers) 
median_value = np.median(random_integers)

#ELEMANLARIN TOPLAMI, ORTALAMASI VE VARYANSI
sum_of_elements = np.sum(random_integers) 
mean_value = np.mean(random_integers) 
variance_value = np.var(random_integers)  

#DİZİDEKİ ÇİFT SAYILARIN VE 5’İN KATI OLAN SAYILARIN SAYISI
even_numbers = random_integers[random_integers % 2 == 0]  # Çift sayılar
even_count = len(even_numbers)  # Çift sayıların sayısı
even_sum = np.sum(even_numbers)  # Çift sayıların toplamı

multiples_of_five = random_integers[random_integers % 5 == 0]  # 5'in katları
multiples_of_five_count = len(multiples_of_five)  # 5'in katlarının sayısı
multiples_of_five_sum = np.sum(multiples_of_five)  # 5'in katlarının toplamı

#BÜYÜKTEN KÜÇÜĞE SIRALAMASI
sorted_descending = np.sort(random_integers)[::-1] 

#ORTALAMANIN ÜZERINDE
above_mean = random_integers[random_integers > mean_value]

#ELEMANLARININ KÜPÜ
cubed_values_of_elements = random_integers ** 3 #elemanlarının küpü

# DIZI ELEMANLARINI 4 DEFA YAN YANA 4’ER DEFA ALT ALTA YAZDIRARAK DIZIYI 2 BOYUTLU
## Tiling the array 4 times in the vertical and 4 times in the horizontal direction 
reshaped_array = np.tile(random_integers, (4, 4))

# Sonuçları yazdırın
print(f"Orijinal Dizi:\n{random_integers}")
print(f"En Küçük Değer: {min_value}")
print(f"En Büyük Değer: {max_value}")
print(f"Medyan Değer: {median_value}")
print(f"Toplam: {sum_of_elements}")
print(f"Ortalama: {mean_value}")
print(f"Varyans: {variance_value}")

print(f"Çift Sayılar: {even_numbers}, Sayısı: {even_count}, Toplamı: {even_sum}")
print(f"5'in Katları: {multiples_of_five}, Sayısı: {multiples_of_five_count}, Toplamı: {multiples_of_five_sum}")

print(f"Büyükten Küçüğe Sıralı Dizi:\n{sorted_descending}")
print(f"Ortalamanın Üzerindeki Elemanlar:\n{above_mean}")
print(f"Küp Alınmış Değerler Dizi:\n{cubed_values_of_elements}")
print(f"Yeniden Şekillendirilmiş (DIZI ELEMANLARINI 4 DEFA YAN YANA 4’ER DEFA ALT ALTA ) Dizi:\n{reshaped_array}")


Orijinal Dizi:
[ 12  74  42  98  56  98  72  48  29  70  43  33  87  98   3   1  57  44
  66  57  69 100   8  11  12  88  38  89  36  71]
En Küçük Değer: 1
En Büyük Değer: 100
Medyan Değer: 56.5
Toplam: 1610
Ortalama: 53.666666666666664
Varyans: 933.3555555555556
Çift Sayılar: [ 12  74  42  98  56  98  72  48  70  98  44  66 100   8  12  88  38  36], Sayısı: 18, Toplamı: 1060
5'in Katları: [ 70 100], Sayısı: 2, Toplamı: 170
Büyükten Küçüğe Sıralı Dizi:
[100  98  98  98  89  88  87  74  72  71  70  69  66  57  57  56  48  44
  43  42  38  36  33  29  12  12  11   8   3   1]
Ortalamanın Üzerindeki Elemanlar:
[ 74  98  56  98  72  70  87  98  57  66  57  69 100  88  89  71]
Küp Alınmış Değerler Dizi:
[   1728  405224   74088  941192  175616  941192  373248  110592   24389
  343000   79507   35937  658503  941192      27       1  185193   85184
  287496  185193  328509 1000000     512    1331    1728  681472   54872
  704969   46656  357911]
Yeniden Şekillendirilmiş (DIZI ELEMANLARINI 4 DE