In [1]:
from datetime import datetime

"""
1. Python	Sınıfı	Oluşturma
"""

class Kitap:
    def __init__(self, baslik: str, yazar: str, yayin_yili: int, sayfa_sayisi: int, diller: list[str]):
        self.baslik = baslik
        self.yazar = yazar
        self.yayin_yili = yayin_yili
        self.sayfa_sayisi = sayfa_sayisi
        self.diller = diller

    def dil_ekle(self, dil: str):
        self.diller.append(dil) #Yeni bir dil ekler.

    def kitap_yasi_hesapla(self) -> int:
        return datetime.now().year - self.yayin_yili #Kitabın yaşını yayın yılına göre hesaplaması

    def kitap_goruntule(self, paragraf: bool = False):
        if paragraf:
            print(
                f"'{self.baslik}' başlıklı kitap, {self.yazar} tarafından yazılmıştır. "
                f"İlk olarak {self.yayin_yili} yılında yayımlanmış olan bu kitap, toplam {self.sayfa_sayisi} sayfadan oluşmaktadır. "
                f"Şu an için bu kitap, {', '.join(self.diller)} dillerinde bulunmaktadır."
            )
        else:
            # Satır bazlı görüntüleme
            print(f"Başlık: {self.baslik}")
            print(f"Yazar: {self.yazar}")
            print(f"Yayın Yılı: {self.yayin_yili}")
            print(f"Sayfa Sayısı: {self.sayfa_sayisi}")
            print(f"Diller: {', '.join(self.diller)}")

kitap = Kitap(
   baslik="Programlama Temelleri",
   yazar="Olvanot Jean Claude Rakotonirina",
   yayin_yili=2005,
   sayfa_sayisi=92,
   diller=["Türkçe", "İngilizce"]
)

kitap.dil_ekle("Fransızca")
kitap.kitap_goruntule(paragraf=True)
kitap.kitap_goruntule(paragraf=False)

'Programlama Temelleri' başlıklı kitap, Olvanot Jean Claude Rakotonirina tarafından yazılmıştır. İlk olarak 2005 yılında yayımlanmış olan bu kitap, toplam 92 sayfadan oluşmaktadır. Şu an için bu kitap, Türkçe, İngilizce, Fransızca dillerinde bulunmaktadır.
Başlık: Programlama Temelleri
Yazar: Olvanot Jean Claude Rakotonirina
Yayın Yılı: 2005
Sayfa Sayısı: 92
Diller: Türkçe, İngilizce, Fransızca


In [2]:
import numpy as np

In [3]:
matrix = np.random.randint(0, 100, (10, 10)) # 10x10 boyutunda rastgele tam sayı

In [4]:
"""
2. Gelişmiş NumPy İşlemleri
"""
row_dict = dict()

for i in range(10):
    min_value = np.min(matrix[i])
    max_value = np.max(matrix[i])
    
    min_index = np.argmin(matrix[i]) 
    max_index = np.argmax(matrix[i])
    
    # Satırların min, max değerleri ve indekslerini sözlükte tutulması
    row_dict[i] = [(min_value, min_index), (max_value, max_index)]
    
print(matrix)
print("Min/Max Değerleri ve İndeksleri")
print(row_dict)

[[43 87 43 72 26  0 70 81 43 38]
 [16 21 23 70 64 57 55 18 62 17]
 [45 20 96 62  6 48 59  2 11  6]
 [ 1 63 31 43 42 83 14 99 31  6]
 [89 56 56 55 32 30 47 38 70 49]
 [63 25 17 91 12 88 13 52 41 88]
 [81 16 13  8 90 80 76 75 70 89]
 [14 39 78 26 47 19 74 68 20 35]
 [ 0 29 89 99 25 93 61 42 26 37]
 [61 58 22 42 56 37 33  3 95 16]]
Min/Max Değerleri ve İndeksleri
{0: [(np.int32(0), np.int64(5)), (np.int32(87), np.int64(1))], 1: [(np.int32(16), np.int64(0)), (np.int32(70), np.int64(3))], 2: [(np.int32(2), np.int64(7)), (np.int32(96), np.int64(2))], 3: [(np.int32(1), np.int64(0)), (np.int32(99), np.int64(7))], 4: [(np.int32(30), np.int64(5)), (np.int32(89), np.int64(0))], 5: [(np.int32(12), np.int64(4)), (np.int32(91), np.int64(3))], 6: [(np.int32(8), np.int64(3)), (np.int32(90), np.int64(4))], 7: [(np.int32(14), np.int64(0)), (np.int32(78), np.int64(2))], 8: [(np.int32(0), np.int64(0)), (np.int32(99), np.int64(3))], 9: [(np.int32(3), np.int64(7)), (np.int32(95), np.int64(8))]}


In [5]:
# Her sütunun ortalama, medyan ve standart sapma 
col_dict = dict()
for col_index in range(10):
    column_mean = np.mean(matrix[:, col_index])
    column_median = np.median(matrix[:, col_index])
    column_standart_deviation = np.std(matrix[:, col_index]) 
    
    col_dict[col_index] = {
        'mean': column_mean,
        'median': column_median,
        'standartDeviation': column_standart_deviation 
    }
print(matrix)
print("Her sütunun ortalama, medyan ve standart sapma değerleri:")
print(col_dict)


[[43 87 43 72 26  0 70 81 43 38]
 [16 21 23 70 64 57 55 18 62 17]
 [45 20 96 62  6 48 59  2 11  6]
 [ 1 63 31 43 42 83 14 99 31  6]
 [89 56 56 55 32 30 47 38 70 49]
 [63 25 17 91 12 88 13 52 41 88]
 [81 16 13  8 90 80 76 75 70 89]
 [14 39 78 26 47 19 74 68 20 35]
 [ 0 29 89 99 25 93 61 42 26 37]
 [61 58 22 42 56 37 33  3 95 16]]
Her sütunun ortalama, medyan ve standart sapma değerleri:
{0: {'mean': np.float64(41.3), 'median': np.float64(44.0), 'standartDeviation': np.float64(30.728000260348868)}, 1: {'mean': np.float64(41.4), 'median': np.float64(34.0), 'standartDeviation': np.float64(22.32129028528593)}, 2: {'mean': np.float64(46.8), 'median': np.float64(37.0), 'standartDeviation': np.float64(29.556048450359526)}, 3: {'mean': np.float64(56.8), 'median': np.float64(58.5), 'standartDeviation': np.float64(26.693819509392057)}, 4: {'mean': np.float64(40.0), 'median': np.float64(37.0), 'standartDeviation': np.float64(24.1039415863879)}, 5: {'mean': np.float64(53.5), 'median': np.float64(52

In [6]:
"""
3. Matris	Çarpımı
"""

def max_in_rows_of_product(matrix_A, matrix_B):
    matrix_AxB = np.dot(matrix_A, matrix_B)
    max_values_in_rows = np.max(matrix_AxB, axis=1)    
    print(matrix_AxB)
    return max_values_in_rows

matrix_A = np.array([[2, 3, 4], [1, 0, 6]])
matrix_B = np.array([[1, 4], [2, 5], [3, 6]])

max_values = max_in_rows_of_product(matrix_A, matrix_B)

print("Sonuç: Matris A x Matris B çarpımındaki her satırın en büyük değerleri:")

print(max_values)


[[20 47]
 [19 40]]
Sonuç: Matris A x Matris B çarpımındaki her satırın en büyük değerleri:
[47 40]


In [7]:
"""
4. Faktöriyel	Hesaplama
"""
def factorial_with_loop(n):
    if n < 0:
        return "Faktöriyel yalnızca pozitif tam sayı olmalıdır!"
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

def factorial(n):
    if n < 0:
        return "Faktöriyel yalnızca pozitif tam sayı olmalıdır!"
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

number=10
print(f"{number}! = {factorial_with_loop(number)}")
print(f"{number}! = {factorial(number)}")


10! = 3628800
10! = 3628800


In [8]:
"""
5. Rasgele	Dizi İşlemleri
Yaklaşım: Tek Sayılara 1 Ekleme
Bu yöntemde, tek sayılara 1 eklenerek çift yapılır, çift sayılar ise olduğu gibi bırakılır

Eğer random_integers = [3, 4, 7, 8] ise:
random_integers % 2 → [1, 0, 1, 0]
(3 ve 7 için kalan 1, 4 ve 8 için 0.)
random_integers + (random_integers % 2) → [4, 4, 8, 8]
"""
random_integers = np.random.randint(1, 21, (5, 4))
print("***Rasgele dizi:***")
print(random_integers)
row_sums = np.sum(random_integers, axis=1)  
row_means = np.mean(random_integers, axis=1) 
row_stats = np.column_stack((row_sums, row_means))  # we can use  np.vstack((row_sums, row_means)).T and Transposing

print("***Satır toplamları***")
print(row_sums)
print("***Satır ortalamaları***")
print(row_means)
# print("******")
print("Satırların Toplam ve Ortalamaları:\n", row_stats)

column_max = np.max(random_integers, axis=0) 
column_min = np.min(random_integers, axis=0)
column_max_min = np.column_stack((column_max, column_min))  # Yeni bir dizi oluştur
print("Sütunların Maksimum ve Minimum Değerleri:\n", column_max_min)

even_matrix = random_integers + (random_integers % 2)
print("Çift matris:\n", even_matrix)


***Rasgele dizi:***
[[ 3 13 19 18]
 [15 13  6  1]
 [ 4 14  3 11]
 [ 9  8 10 16]
 [ 3 16  8  8]]
***Satır toplamları***
[53 35 32 43 35]
***Satır ortalamaları***
[13.25  8.75  8.   10.75  8.75]
Satırların Toplam ve Ortalamaları:
 [[53.   13.25]
 [35.    8.75]
 [32.    8.  ]
 [43.   10.75]
 [35.    8.75]]
Sütunların Maksimum ve Minimum Değerleri:
 [[15  3]
 [16  8]
 [19  3]
 [18  1]]
Çift matris:
 [[ 4 14 20 18]
 [16 14  6  2]
 [ 4 14  4 12]
 [10  8 10 16]
 [ 4 16  8  8]]


In [9]:
"""
Büyük	NumPy	Dizisi	Analizi
"""
#Dizideki en küçük, en büyük ve medyan değeri
min_value = np.min(random_integers) 
max_value = np.max(random_integers) 
median_value = np.median(random_integers)  

# Elemanların toplamını, ortalamasını ve varyansı
sum_of_elements = np.sum(random_integers) 
mean_value = np.mean(random_integers) 
variance_value = np.var(random_integers) 

even_numbers = random_integers[random_integers % 2 == 0]  # Çift sayılar
multiples_of_five = random_integers[random_integers % 5 == 0]  # 5'in katları

even_count = len(even_numbers) 
even_sum = np.sum(even_numbers)  # Çift sayıların toplamı
multiples_of_five_count = len(multiples_of_five)  
multiples_of_five_sum = np.sum(multiples_of_five)  

sorted_integers = np.sort(random_integers)[::-1]  # Büyükten küçüğe sıralı dizi

above_mean_integers = random_integers[random_integers > mean_value]  # Ortalama üzeri elemanlar

cubed_array = random_integers ** 3  # Her elemanın küpü

reshaped_array = np.tile(random_integers, (4, 4))  # 4 kez yan yana, 4 kez alt alta

# Sonuçların yazdırılması
print(f"Orijinal Dizi: {random_integers}")
print(f"En Küçük Değer: {min_value}")
print(f"En Büyük Değer: {max_value}")
print(f"Medyan Değer: {median_value}")
print(f"Toplam: {sum_of_elements}")
print(f"Ortalama: {mean_value}")
print(f"Varyans: {variance_value}")
print(f"Çift Sayılar: {even_numbers}, Sayısı: {even_count}, Toplamı: {even_sum}")
print(f"5'in Katları: {multiples_of_five}, Sayısı: {multiples_of_five_count}, Toplamı: {multiples_of_five_sum}")
print(f"Büyükten Küçüğe Sıralı Dizi: {sorted_integers}")
print(f"Ortalamanın Üzerindeki Elemanlar: {above_mean_integers}")
print(f"Küp Alınmış Dizi: {cubed_array}")
print(f"Yeniden Şekillendirilmiş (4x4) Dizi:\n{reshaped_array}")


Orijinal Dizi: [[ 3 13 19 18]
 [15 13  6  1]
 [ 4 14  3 11]
 [ 9  8 10 16]
 [ 3 16  8  8]]
En Küçük Değer: 1
En Büyük Değer: 19
Medyan Değer: 9.5
Toplam: 198
Ortalama: 9.9
Varyans: 28.490000000000002
Çift Sayılar: [18  6  4 14  8 10 16 16  8  8], Sayısı: 10, Toplamı: 108
5'in Katları: [15 10], Sayısı: 2, Toplamı: 25
Büyükten Küçüğe Sıralı Dizi: [[ 3  8  8 16]
 [ 8  9 10 16]
 [ 3  4 11 14]
 [ 1  6 13 15]
 [ 3 13 18 19]]
Ortalamanın Üzerindeki Elemanlar: [13 19 18 15 13 14 11 10 16 16]
Küp Alınmış Dizi: [[  27 2197 6859 5832]
 [3375 2197  216    1]
 [  64 2744   27 1331]
 [ 729  512 1000 4096]
 [  27 4096  512  512]]
Yeniden Şekillendirilmiş (4x4) Dizi:
[[ 3 13 19 18  3 13 19 18  3 13 19 18  3 13 19 18]
 [15 13  6  1 15 13  6  1 15 13  6  1 15 13  6  1]
 [ 4 14  3 11  4 14  3 11  4 14  3 11  4 14  3 11]
 [ 9  8 10 16  9  8 10 16  9  8 10 16  9  8 10 16]
 [ 3 16  8  8  3 16  8  8  3 16  8  8  3 16  8  8]
 [ 3 13 19 18  3 13 19 18  3 13 19 18  3 13 19 18]
 [15 13  6  1 15 13  6  1 15 13  6